### ISSUE TITLE
CaptainDuckDuck stuck on saving tar file

### ISSUE THREAD

**Issue by guppythegod** [githubsaturn/captainduckduck#328] opened 2018-11-26 04:45 UTC
IMPORTANT: DO NOT POST issues that are not specific to CaptainDuckDuck. Issues and questions related to Docker will get closed.

> If you are trying to see how to deploy a particular app using dockerfileLines property - please change your questions to Dockerfile and post it where appropriate such as Stackoverflow. This is not a CaptainDuckDuck related issue.

What is the problem?

CaptainDuckDuck deploy stuck on "saving tar". This is happening to all of my captainduckduck deployements, so I'm guessing its something with the CLI. Everything was working fine up until 5 minutes before posting this.

I also tried uninstalling and reinstalling CaptainDuckDuck CLI and the problem happened agin.

If applicable, content of `captain-definition` file:

 {
  "schemaVersion" :1 ,
  "templateId" :"node/8.7.0"
 }

Steps to reproduce the problem:

"captainduckduck deploy"

Answers to the following questions where applicable:
- Your OS and version? Windows 10
- RAM? 16 GB

**Comment by githubsaturn** [comment] 2018-11-26 08:12
Last time we updated Captain CLI was 6 months ago. This is unlikely be due to a Captain CLI bug. Can you run the following command from your repo and see if it outputs the tar file successfully?
```
git archive --format tar --output "./test.tar" master
```

**Comment by githubsaturn** [comment] 2018-11-27 01:35
What do you mean by "nothing happened"? Did running the `git archive --format tar --output "./test.tar" master` result in creating `test.tar` file that contained your repository? Or did it freeze? Or it errored out?

**Comment by githubsaturn** [comment] 2018-12-10 19:53
I am closing this issue in favor of https://github.com/githubsaturn/captainduckduck/issues/335

The root cause is the same and we have more information on the other issue.

**Closed** 2018-12-10 19:53 UTC
Labels: duplicate
