### ISSUE TITLE
nice to support dockfile directly rather than captain definition file

### ISSUE THREAD

**Issue by williamhatch** [githubsaturn/captainduckduck#305] opened 2018-10-30 19:42 UTC
It will be nice if not necessary to convert that.

**Comment by githubsaturn** [comment] 2018-10-31 00:14
Please check out the open issues before submitting a new one. Duplicate of https://github.com/githubsaturn/captainduckduck/issues/113

**Closed by githubsaturn** 2018-10-31 00:14 UTC
