### ISSUE TITLE
Still fail one click install wordpress

### ISSUE THREAD

**Issue by yogi-indragiri** [githubsaturn/captainduckduck#236] opened 2018-05-14 07:32 UTC
<img width="555" alt="screen shot 2018-05-14 at 14 24 11" src="https://user-images.githubusercontent.com/17782059/39983746-f35c80fc-5782-11e8-950a-510b3fe3ccac.png">

Hai, i'd like to ask, why i still get error 502 after install wordpress in one click apps/database ? 
I have update captain version to V 0.7.1

**Comment by aramix** [comment] 2018-05-14 11:37
wp 4.9 requires mysql 5.6, in the one click-app section the default value for mysql is 5.5. However, even if changed to 5.6 manually, that does not fix the problem. Still error 502 is shown.

**Comment by iamrommel** [comment] 2018-05-14 11:57
What does your docker service logs  says?

P.s. Check from the wiki on how to troubleshoot

**Comment by aramix** [comment] 2018-05-14 12:31
@iamrommel 
| MySQL Connection Error: (2054) The server requested authentication method unknown to the client
srv-captain--lawless.1.zy4vl3s37x1z@docker-s-2vcpu-4gb-nyc1-01    |
srv-captain--lawless.1.zy4vl3s37x1z@docker-s-2vcpu-4gb-nyc1-01    | Warning: mysqli::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in Standard input code on line 22

**Comment by aramix** [comment] 2018-05-14 13:11
I just found out that this issue seems to be a duplicate of #233 and the problem comes from laradock images. Any fix for this?

**Comment by githubsaturn** [comment] 2018-05-14 14:59
AFAIK, WordPress works with any 5.x version of MySQL.

Note that if you installed a version 8 previously, you have to either manually remove the volume or use a different name for your database app name. Otherwise, the authentication table will have the same issue as will use the same persistent directory (volume). I guess this is what happened to you.

**Closed by githubsaturn** 2018-05-14 14:59 UTC

**Comment by githubsaturn** [comment] 2018-05-14 15:00
I'll retest creating a WordPress with default tags tonight and if it doesn't work, I'll update the default to 5.7.

**Comment by githubsaturn** [comment] 2018-05-15 06:15
I retested this on a brand new server. Keeping everything at default and it worked fine. To fix the issue, you need to remove the old volumes:
https://github.com/githubsaturn/captainduckduck/wiki/App-Configuration#removing-persistent-apps
Or simply use a brand new app name for your wordpress container.
