### ISSUE TITLE
NetData: something went wrong...

### ISSUE THREAD

**Issue by drmrbrewer** [githubsaturn/captainduckduck#176] opened 2018-02-10 08:11 UTC
On one of my Captain machines, now when I click on Open NetData, now the web page that opens just says:

> Something went wrong...

On the server concerned:

	# docker ps
	CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
	2902dcaeb290        dockersaturn/certbot-sleeping:v0.17.0   "/bin/sh -c 'sleep 9…"   3 hours ago         Up 3 hours          80/tcp, 443/tcp     captain-certbot.1.qqvm9dqwdferpko2giq1jtgjp
	c412265b9839        nginx:latest                            "nginx -g 'daemon of…"   3 hours ago         Up 3 hours          80/tcp              captain-nginx.1.szj00llkmw9t2ewbxi2mrhoip
	957a11e3b894        dockersaturn/captainduckduck:0.5.4      "npm start"              3 hours ago         Up 3 hours          3000/tcp            captain-captain.1.afg5tb00ov91xigowsmj7f0g7
	b08707837d22        titpetric/netdata:1.8                   "/run.sh"                4 days ago          Up 3 hours          19999/tcp           captain-netdata-container

	# docker service ls
	ID                  NAME                  MODE                REPLICAS            IMAGE                                   PORTS
	jhxel1doz9bg        captain-captain       replicated          1/1                 dockersaturn/captainduckduck:0.5.4      *:3000->3000/tcp
	qh8mbv0xjheh        captain-certbot       replicated          1/1                 dockersaturn/certbot-sleeping:v0.17.0   
	izo1kd9nuwn3        captain-nginx         replicated          1/1                 nginx                                   *:80->80/tcp,*:443->443/tcp

Some of the `CREATED` times are odd, because 3 hours ago I was fast asleep...

**Comment by githubsaturn** [comment] 2018-02-10 17:43
What happened: probably your server got rebooted
How to resolve NetData issue: Login to dashboard and turn off NetData, wait for 5 seconds, turn it back on.
Why NetData has a problem and all other apps are fine: This goes back to the fact that Docker does not support `cap-add` flag for services. Therefore, NetData is created as a plain container, not a service. All other apps are created as a service and they are much more resilient and reliable on restart events.
Can Captain solve this: Unless Docker addresses this issue, no.

**Comment by drmrbrewer** [comment] 2018-02-10 20:04
With turn off NetData I just get the oscillating circle for a minute, then it goes back to the Monitor page with the Turn Off and Open buttons still present as before.  i.e. nothing happens.  Should I just do a `docker rm` on the container?

**Comment by githubsaturn** [comment] 2018-02-10 20:13
Do you get a dialog pop-up message saying that NetData is turned off or not?

**Comment by githubsaturn** [comment] 2018-02-10 20:15
Also, try reloading the page and log in again, and see if the problem still exists.

**Comment by drmrbrewer** [comment] 2018-02-10 20:16
No, I get:

![image](https://user-images.githubusercontent.com/9009792/36066293-33878456-0e9f-11e8-97ea-4e08afbe2486.png)

Have tried reloading and trying again, same result.

**Comment by githubsaturn** [comment] 2018-02-10 20:19
You probably found a bug. To see what's going on, please ssh to your server, and run
```
docker service logs captain-captain --since 10m --follow
```

While you have your SSH session active, please retry the process. This time, hopefully, you'll see some logs, indicating what the issue is.

**Comment by drmrbrewer** [comment] 2018-02-10 20:22
captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 302 0.373 ms - 72
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 200 0.592 ms - 36
	captain-captain.1.afg5tb00ov91@myserver    | February 10th 2018, 8:20:36.851 pm    Ensuring Stopped & Removed Container: captain-netdata-container
	captain-captain.1.afg5tb00ov91@myserver    | GET /api/v1/user/system/loadbalancerinfo 200 5.003 ms - 170
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 302 0.823 ms - 72
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 200 0.653 ms - 36
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 302 0.405 ms - 72
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 200 0.655 ms - 36
	captain-captain.1.afg5tb00ov91@myserver    | GET /api/v1/user/system/loadbalancerinfo 200 6.450 ms - 170
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 302 0.401 ms - 72
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 200 2.946 ms - 36
	captain-captain.1.afg5tb00ov91@myserver    | POST /api/v1/user/system/netdata - - ms - -
	captain-captain.1.afg5tb00ov91@myserver    | GET /api/v1/user/system/loadbalancerinfo 200 10.672 ms - 170
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 302 0.893 ms - 72
	captain-captain.1.afg5tb00ov91@myserver    | GET /checkhealth 200 0.584 ms - 36

**Comment by githubsaturn** [comment] 2018-02-10 20:31
Really?! No errors here :frowning: 


As a last step, let's try to check your config, run `cat /captain/config.conf` and look for `netDataInfo` object, and copy the object content here please.

**Comment by githubsaturn** [comment] 2018-02-10 20:33
Are you on the latest version of CaptainDuckDuck?

**Comment by drmrbrewer** [comment] 2018-02-10 20:34
"netDataInfo": {
                "isEnabled": true,
                "data": {
                        "smtp": {
                                "username": "",
                                "password": "mypassword"
                        }
                }
        }

Not sure how I ended up with just a password entered into the netdata config (it is a genuine password... I changed it above for posting), but there we go!

**Comment by drmrbrewer** [comment] 2018-02-10 20:34
Current Version: 0.5.4
    Latest Stable Version: 0.5.4

**Comment by githubsaturn** [comment] 2018-02-10 20:39
This is really confusing. I don't understand why there are no error logs when you get an error.

Are you familiar with Chrome network inspector? Can you see what's is being returned from `/netdata/` endpoint when you try to turn off NetData? This is what it normally should be:
![image](https://user-images.githubusercontent.com/10582082/36066500-68730126-0e5f-11e8-9f39-51190f63da25.png)

**Comment by drmrbrewer** [comment] 2018-02-10 20:42
![image](https://user-images.githubusercontent.com/9009792/36066525-f85351e0-0ea2-11e8-9765-1aa4f9c4eb80.png)

**Comment by drmrbrewer** [comment] 2018-02-10 20:45
![image](https://user-images.githubusercontent.com/9009792/36066539-42ba3a1e-0ea3-11e8-9722-e008c7e1407c.png)

**Comment by githubsaturn** [comment] 2018-02-10 20:45
Finally, one error! Awesome thanks, I'll look into this.

What provider you're using for your server?

**Comment by drmrbrewer** [comment] 2018-02-10 20:46
[Hetzner](https://www.hetzner.com/cloud) -- awesome BTW -- and super value for money too!

**Comment by githubsaturn** [comment] 2018-02-10 20:48
Great! My wild guess is there is dead-lock somewhere in Captain or Docker.
First, try restarting Captain by `docker service update captain-captain --force`

If this doesn't solve it, try re-booting your server. Hopefully, this solves the issue.

**Comment by drmrbrewer** [comment] 2018-02-10 20:58
Restarting Captain didn't help -- turning off netdata has the same effect... i.e. nothing.  Can't I just remove the NetData container and Captain will recognise this when it looks again?

**Comment by githubsaturn** [comment] 2018-02-10 21:03
If you manually remove the NetData container, you'll also have to manually set the `isEnabled` flag in the config.conf file to false by `nano /captain/config.conf`

HOWEVER, if restarting Captain didn't help, it means the "potential" deadlock is in Docker. Therefore, you might not be able to re-start NetData again. But let's give it a shot anyways.

Did you try rebooting the server?

**Comment by drmrbrewer** [comment] 2018-02-10 21:05
> Did you try rebooting the server?

Not yet... which shall I try first?  Reboot or remove NetData container?

**Comment by githubsaturn** [comment] 2018-02-10 21:05
remove NetData container, please.

**Comment by drmrbrewer** [comment] 2018-02-10 21:12
# docker rm b08707837d22 --force

Now it's gone... but strangely, when I go into `/captain/config.conf` (without making any edits), I see:

        "netDataInfo": {
                "isEnabled": false,
                "data": {
                        "smtp": {
                                "username": "",
                                "password": "mypassword"
                        }
                }
        }

**Comment by drmrbrewer** [comment] 2018-02-10 21:12
So it set itself to false.

Is it safe now to try and Start NetData Engine again?

**Comment by githubsaturn** [comment] 2018-02-10 21:16
It's not unsafe. It may or may not work depending on whether the Docker deadlock bug was fixed by this removal or not. Let's give it a shot.


More info if you're interested in what happened: 
That makes sense to me now. You asked Captain to turn off NetData, Captain asked Docker to remove NetData and once Docker says OK, Captain sets the `isEnabled` flag to `false`. The problem was that Docker API had a dead lock. It waited for minutes on the call to "remove NetData", but when you forcefully removed it, it got back to Captain the told Captain that the Container is removed. Now, Captain sets that value to false.

**Comment by githubsaturn** [comment] 2018-02-10 21:21
Found it! The bug is here: this call never returns for NetData: https://docs.docker.com/engine/api/v1.30/#operation/ContainerWait

It's either NetData container not acknowledging the request to stop, or it's a Docker bug. Regardless I'll put a timout on this call to make sure it doesn't take more than 10sec.

Thanks a lot for helping me out in tracking this bug down.

**Comment by drmrbrewer** [comment] 2018-02-10 21:22
Tried to turn on via console...

Captain console message: `Error: please try again`.

Captain logs on server:

	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:20:08.530 pm    Ensuring Stopped & Removed Container: captain-netdata-container
	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:20:08.536 pm    Container already stopped: captain-netdata-container
	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:20:08.550 pm    Creating Sticky Container: titpetric/netdata:1.8
	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:20:10.147 pm    Error: (HTTP code 403) unexpected - endpoint with name captain-netdata-container already exists in network captain-overlay-network 
	captain-captain.1.u779n55ycs0x@myserver    | Error: (HTTP code 403) unexpected - endpoint with name captain-netdata-container already exists in network captain-overlay-network 
	captain-captain.1.u779n55ycs0x@myserver    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:254:17
	captain-captain.1.u779n55ycs0x@myserver    |     at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:7)
	captain-captain.1.u779n55ycs0x@myserver    |     at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:253:5)
	captain-captain.1.u779n55ycs0x@myserver    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
	captain-captain.1.u779n55ycs0x@myserver    |     at emitNone (events.js:110:20)
	captain-captain.1.u779n55ycs0x@myserver    |     at IncomingMessage.emit (events.js:207:7)
	captain-captain.1.u779n55ycs0x@myserver    |     at endReadableNT (_stream_readable.js:1057:12)
	captain-captain.1.u779n55ycs0x@myserver    |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
	captain-captain.1.u779n55ycs0x@myserver    |     at process._tickCallback (internal/process/next_tick.js:180:9)
	captain-captain.1.u779n55ycs0x@myserver    | POST /api/v1/user/system/netdata 500 1620.994 ms - 21

**Comment by githubsaturn** [comment] 2018-02-10 21:23
Can you run `docker ps -a`? If you see netdata, then run `docker container prune`

**Comment by drmrbrewer** [comment] 2018-02-10 21:24
# docker ps -a
	CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                        PORTS               NAMES
	b1283bfe127d        titpetric/netdata:1.8                   "/run.sh"                3 minutes ago       Created                                           captain-netdata-container

**Comment by githubsaturn** [comment] 2018-02-10 21:25
Yea it still exists, you didn't completely remove it. Run `docker container rm captain-netdata-container --force`, wait for 5 second and then `docker container prune`

**Comment by drmrbrewer** [comment] 2018-02-10 21:25
# docker container prune
    # docker ps -a
    [no netdata]

Same error in Captain console starting netdata again

**Comment by githubsaturn** [comment] 2018-02-10 21:26
Same error you mean 504, right?

**Comment by drmrbrewer** [comment] 2018-02-10 21:29
# docker container rm captain-netdata-container --force
    # docker container prune

Start netdata in console, get red error message in console, then:

    # docker service logs captain-captain --since 10m --follow
	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:27:13.341 pm    Ensuring Stopped & Removed Container: captain-netdata-container
	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:27:13.344 pm    Container not found: captain-netdata-container
	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:27:13.344 pm    Creating Sticky Container: titpetric/netdata:1.8
	captain-captain.1.u779n55ycs0x@myserver    | February 10th 2018, 9:27:14.965 pm    Error: (HTTP code 403) unexpected - endpoint with name captain-netdata-container already exists in network captain-overlay-network 
	captain-captain.1.u779n55ycs0x@myserver    | Error: (HTTP code 403) unexpected - endpoint with name captain-netdata-container already exists in network captain-overlay-network 
	captain-captain.1.u779n55ycs0x@myserver    |     at /usr/src/app/node_modules/docker-modem/lib/modem.js:254:17
	captain-captain.1.u779n55ycs0x@myserver    |     at getCause (/usr/src/app/node_modules/docker-modem/lib/modem.js:284:7)
	captain-captain.1.u779n55ycs0x@myserver    |     at Modem.buildPayload (/usr/src/app/node_modules/docker-modem/lib/modem.js:253:5)
	captain-captain.1.u779n55ycs0x@myserver    |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/docker-modem/lib/modem.js:229:14)
	captain-captain.1.u779n55ycs0x@myserver    |     at emitNone (events.js:110:20)
	captain-captain.1.u779n55ycs0x@myserver    |     at IncomingMessage.emit (events.js:207:7)
	captain-captain.1.u779n55ycs0x@myserver    |     at endReadableNT (_stream_readable.js:1057:12)
	captain-captain.1.u779n55ycs0x@myserver    |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
	captain-captain.1.u779n55ycs0x@myserver    |     at process._tickCallback (internal/process/next_tick.js:180:9)
	captain-captain.1.u779n55ycs0x@myserver    | POST /api/v1/user/system/netdata 500 1624.958 ms - 21

**Comment by githubsaturn** [comment] 2018-02-10 21:34
Yes another Docker issue:
https://github.com/moby/moby/issues/20398

Personally, I haven't tried this, but try:
```
docker network disconnect -f captain-overlay-network captain-netdata-container
```

**Comment by drmrbrewer** [comment] 2018-02-10 21:41
OK here's the sequence:

    # docker ps -a
    [netdata still there]
    # docker container rm captain-netdata-container --force
    # docker container prune
    # docker network disconnect -f captain-overlay-network captain-netdata-container

Start NetData in Console.

![image](https://user-images.githubusercontent.com/9009792/36066922-040dec72-0eab-11e8-970e-7ade6ca7fd3a.png)

**Comment by githubsaturn** [comment] 2018-02-10 22:03
Fixed in https://github.com/githubsaturn/captainduckduck/commit/e34b25a56ff5a759a0238ee11f53904958524acd

**Closed** 2018-02-10 22:03 UTC
Labels: technical-support
